sudo: required
services:
    - docker
    
before_install:
    - docker build -t duledwala/docker-react -f Dockerfile.dev .
    
script:
    - docker run duledwala/docker-react npm run test -- --coverage